import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';

async function generateSMTPSummaryPDF(outputPath) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ size: 'A4', margin: 50 });
            const writeStream = fs.createWriteStream(outputPath);
            doc.pipe(writeStream);

            // Header
            doc.fontSize(26).font('Helvetica-Bold').fillColor('#DC2626').text('AROHAN HEALTH', 50, 50);
            doc.fontSize(12).font('Helvetica').fillColor('#4B5563').text('SMTP Activation & Email Setup Guide', 50, 85);
            doc.fontSize(10).text('Date: April 26, 2026', 50, 100);

            // Horizontal Line
            doc.moveTo(50, 120).lineTo(550, 120).strokeColor('#E5E7EB').lineWidth(1).stroke();

            // Section 1: Domain Verification
            doc.fontSize(16).font('Helvetica-Bold').fillColor('#111827').text('1. Domain Email Verification', 50, 140);
            doc.fontSize(11).font('Helvetica').fillColor('#374151').text('Before the mail server can activate, you must verify ownership:', 50, 165);
            
            doc.circle(60, 190, 3).fill('#DC2626');
            doc.text('Check the email sent from Resellerclub.com to mrudhula.uriti@gmail.com.', 75, 185);
            
            doc.circle(60, 210, 3).fill('#DC2626');
            doc.text('Click the verification link to authorize the domain for mail services.', 75, 205);

            // Section 2: Creating Service Email
            doc.fontSize(16).font('Helvetica-Bold').fillColor('#111827').text('2. Creating your "Sender" Email', 50, 245);
            doc.fontSize(11).font('Helvetica').text('Use the cPanel credentials provided by the DSC Web Team:', 50, 270);
            
            // Credential Box
            doc.rect(50, 290, 500, 70).fill('#F9FAFB');
            doc.fillColor('#111827').font('Helvetica-Bold').text('Login URL:', 70, 305).font('Helvetica').text('http://haspranahealth.com:2095/', 170, 305);
            doc.font('Helvetica-Bold').text('Username:', 70, 325).font('Helvetica').text('haspranahealth', 170, 325);
            doc.font('Helvetica-Bold').text('Password:', 70, 345).font('Helvetica').text('R@,sx-UbS)H$', 170, 345);

            doc.fillColor('#374151').font('Helvetica').text('Action: Open "Email Accounts" in cPanel and create "alerts@haspranahealth.com".', 50, 375);

            // Section 3: Configuration Snippet
            doc.fontSize(16).font('Helvetica-Bold').fillColor('#111827').text('3. Application configuration', 50, 415);
            doc.fontSize(11).font('Helvetica').text('Update the .env.production file on your AWS server with these details:', 50, 440);

            // Code Box
            doc.rect(50, 460, 500, 100).fill('#1F2937');
            doc.fillColor('#10B981').font('Courier').fontSize(10)
               .text('SMTP_HOST=mail.haspranahealth.com', 70, 480)
               .text('SMTP_PORT=587', 70, 495)
               .text('SMTP_USER=alerts@haspranahealth.com', 70, 510)
               .text('SMTP_PASSWORD=R@,sx-UbS)H$', 70, 525);

            // Section 4: Activation
            doc.fontSize(16).font('Helvetica-Bold').fillColor('#111827').text('4. Restart and Activate', 50, 580);
            doc.fontSize(11).font('Helvetica').fillColor('#374151').text('Run the following commands in your server terminal to apply changes:', 50, 605);
            
            doc.rect(50, 625, 500, 45).fill('#F3F4F6');
            doc.fillColor('#374151').font('Courier-Bold').text('cd /home/ubuntu/app && sudo docker compose restart backend', 70, 640);

            // Footer
            doc.moveTo(50, 750).lineTo(550, 750).strokeColor('#E5E7EB').lineWidth(1).stroke();
            doc.fontSize(10).font('Helvetica').fillColor('#9CA3AF').text('Generated by Antigravity AI for Arohan Health Platform', 50, 770, { align: 'center', width: 500 });
            doc.text('Technical Support: support@arohanhealth.com', 50, 785, { align: 'center', width: 500 });

            doc.end();
            writeStream.on('finish', () => resolve(outputPath));
            writeStream.on('error', (err) => reject(err));
        } catch (error) {
            reject(error);
        }
    });
}

const outputPath = path.join(process.cwd(), 'SMTP_Activation_Guide.pdf');
generateSMTPSummaryPDF(outputPath)
    .then(p => console.log(`PDF generated at: ${p}`))
    .catch(e => console.error(e));
