/* eslint-disable no-restricted-globals */
import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

clientsClaim();

// Skip waiting and activate immediately
self.skipWaiting();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
    // Return false to exempt requests from being fulfilled by index.html.
    ({ request, url }) => {
        // If this isn't a navigation, skip.
        if (request.mode !== 'navigate') {
            return false;
        } // If this is a URL that starts with /_, skip.

        if (url.pathname.startsWith('/_')) {
            return false;
        } // If this looks like a URL for a resource, because it contains // a file extension, skip.

        if (url.pathname.match(fileExtensionRegexp)) {
            return false;
        } // Return true to signal that we want to use the handler.

        return true;
    },
    createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Runtime Caching: Images
registerRoute(
    ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'), // Customize this strategy as needed, e.g., by changing to CacheFirst.
    new StaleWhileRevalidate({
        cacheName: 'images',
        plugins: [
            // Ensure that once this runtime cache reaches a maximum size the
            // least-recently used images are removed.
            new ExpirationPlugin({ maxEntries: 50 }),
        ],
    })
);

// API Caching (Network First for freshness, fallback to cache)
registerRoute(
    ({ url }) => url.pathname.startsWith('/v1/'),
    new NetworkFirst({
        cacheName: 'api-cache',
        plugins: [
            new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 24 * 60 * 60 })
        ]
    })
);


// --------------------------------------------------------------------------
// BACKGROUND SYNC (PWA-03)
// --------------------------------------------------------------------------
const bgSyncPlugin = new BackgroundSyncPlugin('arohan-sync-queue', {
    maxRetentionTime: 24 * 60 // Retry for up to 24 hours (in minutes)
});

// Register route for background sync (e.g., submitting forms offline)
registerRoute(
    ({ url, method }) => url.pathname.includes('/submit') || method === 'POST',
    new NetworkFirst({
        plugins: [bgSyncPlugin]
    }),
    'POST'
);


// --------------------------------------------------------------------------
// PUSH NOTIFICATIONS (PWA-04)
// --------------------------------------------------------------------------
self.addEventListener('push', (event) => {
    const data = event.data.json();
    console.log('Push received:', data);

    const title = data.title || 'Arohan Health';
    const options = {
        body: data.body || 'New notification',
        icon: data.icon || '/icon-192.png',
        badge: '/icon-192.png',
        data: data.data || { url: '/' }
    };

    event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            if (clientList.length > 0) {
                let client = clientList[0];
                for (let i = 0; i < clientList.length; i++) {
                    if (clientList[i].focused) {
                        client = clientList[i];
                    }
                }
                return client.focus();
            }
            return self.clients.openWindow(event.notification.data.url);
        })
    );
});

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});
